Add support for RDF Turtle format
spdx/tools-java pull request #82
Opened 2022-10-18 20:16 UTC by goneall

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

2022-10-18 20:39 UTC, goneall commented on src/main/java/org/spdx/tools/SpdxToolsHelper.java
> +	public static SerFileType fileToFileType(File file)
Note that these and subsequent changes are just reformatting

2022-10-19 14:05 UTC, zvr requested changes

2022-10-19 18:05 UTC, goneall commented on src/main/java/org/spdx/tools/SpdxToolsHelper.java
> +				rdfStore.setOutputFormat(OutputFormat.XML);
@zvr Thanks for the catch.  

Hmm - I did test this, not quite sure why it worked.

2022-10-19 18:22 UTC, goneall commented on src/main/java/org/spdx/tools/SpdxToolsHelper.java
> +				rdfStore.setOutputFormat(OutputFormat.XML);
Fixed in commit a8b459a7b89c5ca7c5b2817de19cc10b1b3849f5

2022-10-19 18:22 UTC, merged